### ISSUE TITLE
Some question

### ISSUE THREAD

**Issue by ImChaiNis** [guberti/witness-encryption-demos#3]
Excuse me , Firstly, whether the test set of old/make_puzzle_enc.py is trash.txt? Second,in make_puzzle_enc.py The pieces of def pentomino is not int string and def sudoku_wsol has bug, c of the def mapchar(c) can't be int 

![屏幕截图 2021-12-26 213250](https://user-images.githubusercontent.com/84436726/147409729-bf1fbda3-7d3d-44ab-98b8-b37e4d6574a1.png)
Thank you Hope to hear from you soon！

**Comment by guberti** [comment]
Our work is a preprint, and this GitHub repo is a little messy. All the files in `old` were from previous experimentation, but no longer work. They will likely be removed very soon.

**Comment by ImChaiNis** [comment]
okk, whether it means that codes can't run now ?  and i want to konw when it can renew :) 
thanks for your reply!

**Comment by guberti** [comment]
The code still works! You just need to make sure you're using the C, not the Python implementation. A good first step would be to get the unit test `test_clt_witness_scheme.c` compiling with `make`.
